.PHONY: clean All

All:
	@echo "----------Building project:[ OOP_Lab_1 - Debug ]----------"
	@cd "OOP_Lab_1" && "$(MAKE)" -f  "OOP_Lab_1.mk"
clean:
	@echo "----------Cleaning project:[ OOP_Lab_1 - Debug ]----------"
	@cd "OOP_Lab_1" && "$(MAKE)" -f  "OOP_Lab_1.mk" clean
